apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-svc.fullname" . }}-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "user-svc.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
