apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: basket-api
  name: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basket-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: basket-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: ConnectionStrings__Database
              value: Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
            - name: ConnectionStrings__Redis
              value: distributedcache:6379
            - name: GrpcSettings__DiscountUrl
              value: http://discount-grpc:80
            - name: MessageBroker__Host
              value: amqp://ecommerce-mq:5672
            - name: MessageBroker__Password
              value: guest
            - name: MessageBroker__UserName
              value: guest
          image: trananhtien/basketapi:2.0
          name: basket-api
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
