apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: distributedcache
  name: distributedcache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: distributedcache
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: distributedcache
    spec:
      containers:
        - image: redis
          name: distributedcache
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
