apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: messagebroker
  name: messagebroker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messagebroker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: messagebroker
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: rabbitmq:management
          name: messagebroker
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
      hostname: ecommerce-mq
      restartPolicy: Always
