apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: messagebroker
  name: messagebroker
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: messagebroker
