apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: shopping-web
  name: shopping-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopping-web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 -f docker-compose.yml -f docker-compose.override.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: shopping-web
    spec:
      containers:
        - env:
            - name: ApiSettings__GatewayAddress
              value: http://10.103.179.237:6064
          image: trananhtien/shoppingweb:3.0
          name: shopping-web
          ports:
            - containerPort: 80
             
