apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: yarpapigateway
  name: yarpapigateway
spec:
  ports:
    - name: "6064"
      port: 6064
      targetPort: 80
  selector:
    io.kompose.service: yarpapigateway
