version: '3.4'

services:
  


  yarpapigateway:
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    
    #depends_on:
      #- catalog-api
      #- basket-api
      #- ordering-api
    ports:      
      - "6069:80"

  
      


