name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print working directory
        run: pwd
      - name: Run a simple script
        run: |
          kubectl get all
          echo "Running on $(hostname)"
          dir
      - name: Test a Windows command
        run: |
          echo "Current user: %USERNAME%"
          dir
        shell: cmd

      - name: Test PowerShell script
        run: |
          Write-Host "Testing PowerShell script on self-hosted runner"
          Get-Process | Select-Object -First 5
        shell: pwsh
